/**
 * generated by Xtext
 */
package com.github.thomasfischl.minipascal.ui.contentassist;

import com.github.thomasfischl.minipascal.ui.contentassist.AbstractPascalProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class PascalProposalProvider extends AbstractPascalProposalProvider {
}
