/*
 * generated by Xtext
 */
package com.github.thomasfischl.minipascal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PascalUiModule extends com.github.thomasfischl.minipascal.ui.AbstractPascalUiModule {
	public PascalUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
