/*
 * generated by Xtext
 */
package com.github.thomasfischl.minipascal;

import org.eclipse.xtext.generator.IGenerator;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class PascalRuntimeModule extends
		com.github.thomasfischl.minipascal.AbstractPascalRuntimeModule {

	@Override
	public Class<? extends IGenerator> bindIGenerator() {
		return com.github.thomasfischl.minipascal.generator.PascalGeneratorExt.class;
	}

}
