/*
 * generated by Xtext
 */
package com.github.thomasfischl.minipascal.validation;

import org.eclipse.xtext.validation.Check;

import com.github.thomasfischl.minipascal.pascal.PascalPackage;
import com.github.thomasfischl.minipascal.pascal.VarName;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
public class PascalJavaValidator extends com.github.thomasfischl.minipascal.validation.AbstractPascalJavaValidator {

  // @Check
  // public void checkGreetingStartsWithCapital(VarName name) {
  // if (!name.getName().equals(name.getName().toLowerCase())) {
  // error("Name should start with a capital",
  // PascalPackage.Literals.VAR_NAME__NAME);
  // }
  // }
}
